# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14XDhhw2Im5aR8JU6lrxxlbGpiRIwRBTn
"""

# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qo6k7xbXc3YU_gxumWKJxDwts6fUjkXb
"""

import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,6])
y=np.array([0,250])

plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([1,4,6,8,10])
y=np.array([3,8,1,10,4])
plt.plot(y, marker='h', ms=10)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,0,0,0])
y=np.array([0,0,35,0])

plt.scatter(x,y)
plt.show()



import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,1,2,3,4,5,6])
y=np.array([0,2,8,1,14,7])
plt.scatter(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array(['680-23','682-23','681-23'])
y=np.array([25,10,23])

plt.bar(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([35,50,16,15,5,8,65])

plt.pie(x)
plt.show()



import matplotlib.pyplot as plt
import numpy as np

x=np.array([35,50,16,50,80])

mylabels=['Suniy intelekt','kiber xavsizlik','elektornika va sxemalar','kompyuterni tashkilm  etish','maxsus kurs']

plt.pie(x, labels=mylabels)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([35,50,16,50,80])

mylabels=['Suniy intelekt','kiber xavsizlik','elektornika va sxemalar','kompyuterni tashkilm  etish','maxsus kurs']
myexplode=[0,2,0,0,0]

plt.pie(x)
plt.show()